########################################
# 서버 포트
########################################
server:
  port: 8170

########################################
# 로그 디버깅
########################################
logging:
  level:
    root: DEBUG


########################################
# 서버,핸들러,전문 정보를 읽어올 정보
# path가 있으면 로컬파일에서 읽고, 없으면 url에서 읽어옴.
########################################
carrier:
  path:
    server: config/servers/*.xml
    message: config/messages/*.xml
    handler: config/handlers/*.xml
  url:
    server: http://localhost:8081/servers 
    message: http://localhost:8081/messages
    handler: http://localhost:8081/handlers
  client:
    url: http://localhost:8090/
      
########################################
# 기본 데이터 베이스 연결 정보
########################################
spring:
  datasource:
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:testdb 
    username: sa 
    password: 
    driverClassName: org.h2.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-life-time: 2000000
      connection-time-out: 30000

#    max-active: 10
#    max-idle: 8
#    min-idle: 8
#    initial-size: 5
  h2:
    console:
      enabled: true
  jpa.hibernate:
    ddl-auto: h2.init.sql

############################################
# 마이바티스 직접 설정할 경우
############################################    
# mybatis:
#   config-location=classpath=mybatis-config.xml
      
# mybatis:
#  typeAliasesPackage=com.kcb.id.comm.carrier.mybatis.mapper
#  mapperLocations=classpath*:mappers/**/*.xml